version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gast
    versions:
    - "> 0.2.2, < 1"
  - dependency-name: numpy
    versions:
    - "> 1.16.2, < 2"
  - dependency-name: numpy
    versions:
    - "> 1.17.3, < 1.18"
